name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add dependency repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add cert-manager https://charts.jetstack.io
          helm repo add cilium https://helm.cilium.io
          helm repo add coredns https://coredns.github.io/helm
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add longhorn https://charts.longhorn.io
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
